### basic settings

# site properties and page defaults
title: TISLab
description: Translational and Integrative Sciences Lab
logo: images/logo.svg
header: images/bg-dna.jpg
footer: images/bg-dna.jpg

# site social media and other links
links:
  email: info@tislab.org
  google-scholar: Melissa Haendel
  github: tis-lab
  twitter: ontowonka

### advanced settings

# default front matter parameters for markdown files
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

# collections
collections:
  members:
    output: true

# sass settings
sass:
  sass_dir: css

# syntax highlighting
highlighter: rouge

# plugins
plugins:
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-sitemap
  # - jekyll-github-metadata
  # - jekyll-avatar
  # - jekyll-gist
  # - jekyll-mentions
  # - jekyll-relative-links
  # - jemoji

# jekyll theme
theme: null
